version: 0.2

phases:
  install:
    commands:
    - runtime-versions:
      java: open-jdk
  pre-build:
    commands:
    - echo nothing to do in the pre-build phase
  build:
    commands:
    - echo Build started on 'date'
    - mvn clean deploy
  post_build:
    commands:
    - echo build complete on 'date'
artifacts:
  files:
  - 'target/maven-web-application.war'               
